export default function TermsOfService() {
  return (
    <div style={{ background: '#ffffff', minHeight: '100vh', colorScheme: 'light' }}>
      <main style={{ maxWidth: '760px', margin: '0 auto', padding: '3rem 1.5rem', fontFamily: 'Georgia, serif', color: '#1a1a2e', lineHeight: '1.8' }}>
        <div style={{ marginBottom: '2.5rem', borderBottom: '2px solid #0077b6', paddingBottom: '1.5rem' }}>
          <p style={{ fontSize: '13px', color: '#555', marginBottom: '0.5rem', fontFamily: 'sans-serif', letterSpacing: '0.08em', textTransform: 'uppercase' }}>AquaRef · Legal</p>
          <h1 style={{ fontSize: '2rem', fontWeight: '700', margin: '0 0 0.5rem', color: '#03045e' }}>Terms of Service</h1>
          <p style={{ fontSize: '14px', color: '#777', fontFamily: 'sans-serif' }}>Effective Date: 19 April 2025 &nbsp;·&nbsp; Last Updated: 19 April 2025</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using AquaRef at <strong>aquaref.co</strong> ("the Service"), you agree to be bound by these Terms of Service ("Terms"). The Service is operated by <strong>AquaRef</strong>. If you do not agree with any part of these Terms, you may not use the Service.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>AquaRef is an AI-powered assistant that provides information about World Aquatics rules and regulations for the following disciplines: Swimming, Water Polo, Artistic Swimming, Diving, High Diving, Masters Swimming, Open Water and Para Swimming.</p>
          <p><strong>Important Disclaimer:</strong> AquaRef is an informational tool only. All responses are generated by artificial intelligence based on uploaded rulebook documents. Responses must not be treated as official rulings. Always verify with the official World Aquatics rulebooks and consult the Meet Referee for authoritative decisions.</p>
        </Section>

        <Section title="3. Eligibility">
          <p>You must be at least 13 years of age to use AquaRef. By using the Service, you represent and warrant that you meet this requirement and that you have the legal capacity to enter into these Terms.</p>
        </Section>

        <Section title="4. Subscription Plans & Billing">
          <p>AquaRef offers the following subscription plans:</p>
          <ul>
            <li><strong>AquaRef LITE</strong> — Free forever: access to one (1) discipline, 5 questions per month.</li>
            <li><strong>AquaRef PRO</strong> — RM14.99/month: access to one (1) discipline, 50 questions per day, switch discipline every 30 days.</li>
            <li><strong>AquaRef ELITE</strong> — RM39.99/month: access to all 8 disciplines, unlimited questions per day, instant discipline switching.</li>
          </ul>
          <p>Paid plans include a <strong>7-day free trial</strong>. A valid payment method is required to activate the free trial. You will not be charged until the trial period ends. Subscriptions automatically renew monthly unless cancelled.</p>
          <p>All prices are in Malaysian Ringgit (RM) and are inclusive of any applicable taxes. Payments are processed securely by Stripe.</p>
        </Section>

        <Section title="5. Cancellation & Refunds">
          <p>You may cancel your subscription at any time from your account dashboard. Upon cancellation, you will retain access to the Service until the end of your current billing period. We do not offer refunds for partial billing periods.</p>
          <p>If you believe you have been charged in error, please contact us at <strong>hello@aquaref.co</strong> within 7 days of the charge.</p>
        </Section>

        <Section title="6. Acceptable Use">
          <p>You agree to use AquaRef only for lawful purposes. You must not:</p>
          <ul>
            <li>Share your account credentials or allow others to use your account</li>
            <li>Use automated tools or bots to interact with the Service</li>
            <li>Attempt to reverse-engineer, scrape, or extract data from the Service</li>
            <li>Use the Service to generate misleading or harmful content</li>
            <li>Circumvent any usage limits, access controls, or security measures</li>
            <li>Misrepresent AI-generated responses as official World Aquatics rulings</li>
          </ul>
          <p>We reserve the right to suspend or terminate accounts that violate these terms without prior notice.</p>
        </Section>

        <Section title="7. One Account Per User">
          <p>Each subscription is licensed to a single individual. Account sharing is strictly prohibited. We reserve the right to terminate accounts found to be shared among multiple users without refund.</p>
        </Section>

        <Section title="8. Daily Usage Limits">
          <p>Usage is subject to question limits based on your subscription plan. LITE plan limits reset monthly. PRO and ELITE daily limits reset at midnight (UTC+8, Malaysia Standard Time). Upon reaching your limit, you will be prompted to upgrade your plan or wait for the reset. We reserve the right to adjust usage limits with reasonable notice.</p>
        </Section>

        <Section title="9. AI Limitations & Accuracy">
          <p>AquaRef uses artificial intelligence to answer questions based on uploaded rulebook documents. While we strive for accuracy, AI responses may contain errors, omissions, or outdated information. We make no warranty that responses are complete, accurate, or current.</p>
          <p>Every response includes a reminder to verify information with the official rulebook and the Meet Referee. Reliance on AquaRef responses for official competition decisions is at your own risk.</p>
        </Section>

        <Section title="10. Intellectual Property">
          <p>The AquaRef platform, including its design, code, and branding, is the property of AquaRef. World Aquatics rulebooks are the intellectual property of World Aquatics. Para Swimming rulebooks are the intellectual property of World Para Swimming (WPS) under the International Paralympic Committee (IPC). AquaRef is an independent service and is not affiliated with, endorsed by, or officially connected to World Aquatics or World Para Swimming.</p>
        </Section>

        <Section title="11. Limitation of Liability">
          <p>To the maximum extent permitted by applicable law, AquaRef shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Service. Our total liability to you for any claims arising from these Terms shall not exceed the amount you paid us in the three (3) months preceding the claim.</p>
        </Section>

        <Section title="12. Service Availability">
          <p>We strive to maintain high availability of AquaRef but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or factors beyond our control. We are not liable for any losses resulting from service downtime.</p>
        </Section>

        <Section title="13. Changes to Terms">
          <p>We reserve the right to modify these Terms at any time. We will notify you of material changes by email or by posting a notice on the Service. Your continued use of AquaRef after such changes constitutes your acceptance of the updated Terms.</p>
        </Section>

        <Section title="14. Governing Law">
          <p>These Terms shall be governed by and construed in accordance with the laws of Malaysia. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of Malaysia.</p>
        </Section>

        <Section title="15. Contact Us">
          <p>For questions, complaints, or legal notices regarding these Terms, please contact us:</p>
          <div style={{ background: '#f0f7ff', border: '1px solid #bdd7f0', borderRadius: '8px', padding: '1rem 1.25rem', marginTop: '0.75rem' }}>
            <p style={{ margin: '0 0 4px' }}><strong>AquaRef</strong></p>
            <p style={{ margin: '0 0 4px' }}>Email: <a href="mailto:hello@aquaref.co" style={{ color: '#0077b6' }}>hello@aquaref.co</a></p>
            <p style={{ margin: '0' }}>Website: <a href="https://aquaref.co" style={{ color: '#0077b6' }}>aquaref.co</a></p>
          </div>
        </Section>

        <footer style={{ marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid #ddd', fontSize: '13px', color: '#999', fontFamily: 'sans-serif', textAlign: 'center' }}>
          &copy; {new Date().getFullYear()} AquaRef. All rights reserved.
        </footer>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string, children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: '2rem' }}>
      <h2 style={{ fontSize: '1.1rem', fontWeight: '700', color: '#03045e', marginBottom: '0.75rem', fontFamily: 'sans-serif' }}>{title}</h2>
      <div style={{ fontSize: '15px', color: '#333' }}>{children}</div>
    </section>
  )
}